-- PRD 8.2 / M4 -- LAN direct transfer. A transfer now knows which path it took.
--
-- This is not bookkeeping for its own sake. Three places have to tell the two
-- apart and cannot do it from any other column:
--
--   1. `openTransfer` books the owner's monthly relay allowance. A LAN transfer
--      never touches the relay, so it books nothing -- PRD 16.2 promises the
--      local path is free forever.
--   2. `abandonTransfer` and the expiry sweep refund that allowance. Refunding
--      bytes that were never booked is not a no-op: `refundRelayBytes` clamps
--      at zero, which stops the counter going negative but does nothing to stop
--      it eating allowance that a *different* transfer booked in the same
--      month. Without this column an abandoned LAN transfer silently hands the
--      owner free relay quota.
--   3. `GET /api/v1/files/:fid/meta` only exists for LAN, and must not become a
--      way to read relay metadata early.
--
-- Defaulting to 'relay' is what makes this safe to apply to a live table: every
-- row that already exists went over the relay, and every one of them was booked.
ALTER TABLE transfers ADD COLUMN transport TEXT NOT NULL DEFAULT 'relay';
