/**
 * Generates testdata/vectors.json, read by both scripts/e2e.ts and the Swift
 * test suite.
 *
 * A mismatch between the browser's AES-GCM framing and CryptoKit's — a nonce
 * assembled differently, an AAD field in the wrong byte order, HKDF with the
 * wrong info string — produces files that upload cleanly and fail to decrypt on
 * the Mac. That class of bug is invisible until someone loses a file, so it is
 * pinned down by shared vectors rather than left to integration testing.
 *
 *   node --experimental-strip-types scripts/gen-vectors.ts
 */
import { writeFileSync } from "node:fs";
import {
	CHUNK_SIZE,
	chunkCountFor,
	cipherSizeFor,
	encryptChunk,
	encryptName,
	fileIdBytes,
	fromBase64Url,
	importContentKey,
	newContentKey,
	sealContentKey,
	toBase64Url,
	toHex,
} from "../src/shared/envelope.ts";

/**
 * Deterministic filler, so large plaintexts need not be stored in the vectors.
 * Reimplemented identically in Swift:
 *   block_n = SHA-256(utf8(seed) || uint32_be(n)), concatenated, truncated.
 */
async function seededBytes(seed: string, length: number): Promise<Uint8Array> {
	const out = new Uint8Array(length);
	const seedBytes = new TextEncoder().encode(seed);
	let offset = 0;
	let counter = 0;
	while (offset < length) {
		const input = new Uint8Array(seedBytes.length + 4);
		input.set(seedBytes, 0);
		new DataView(input.buffer).setUint32(seedBytes.length, counter, false);
		const block = new Uint8Array(await crypto.subtle.digest("SHA-256", input));
		const take = Math.min(block.length, length - offset);
		out.set(block.subarray(0, take), offset);
		offset += take;
		counter += 1;
	}
	return out;
}

async function encryptStream(
	contentKey: CryptoKey,
	noncePrefix: Uint8Array,
	fileId: string,
	plaintext: Uint8Array,
): Promise<Uint8Array> {
	const total = chunkCountFor(plaintext.length);
	const out = new Uint8Array(cipherSizeFor(plaintext.length));
	let offset = 0;
	for (let index = 0; index < total; index++) {
		const chunk = plaintext.subarray(index * CHUNK_SIZE, (index + 1) * CHUNK_SIZE);
		const ct = await encryptChunk(contentKey, {
			noncePrefix,
			fileIdBytes: fileIdBytes(fileId),
			index,
			total,
			plaintext: chunk,
		});
		out.set(ct, offset);
		offset += ct.length;
	}
	if (offset !== out.length) throw new Error(`framing mismatch: ${offset} vs ${out.length}`);
	return out;
}

const recipient = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, [
	"deriveBits",
]);
const recipientJwk = await crypto.subtle.exportKey("jwk", recipient.privateKey);
const recipientPubRaw = toBase64Url(
	new Uint8Array(await crypto.subtle.exportKey("raw", recipient.publicKey)),
);

const contentKey = await newContentKey();
const contentKeyRaw = new Uint8Array(await crypto.subtle.exportKey("raw", contentKey));
const envelope = await sealContentKey(recipientPubRaw, contentKey);
const noncePrefix = fromBase64Url(envelope.nonce_prefix);

const filename = "客户素材 final ✅.mov";
const name = await encryptName(contentKey, filename);

const fileId = toBase64Url(crypto.getRandomValues(new Uint8Array(16)));

interface Vector {
	label: string;
	file_id: string;
	size: number;
	/** Inline plaintext, or null when it comes from `seed`. */
	plaintext?: string;
	seed?: string;
	ciphertext: string;
	plain_sha256: string;
	chunk_count: number;
}

const vectors: Vector[] = [];

// Boundary sizes: empty, single byte, sub-chunk, exactly one chunk, and a
// multi-chunk file whose last chunk is short.
for (const [label, size] of [
	["empty", 0],
	["one-byte", 1],
	["sub-chunk", 1023],
	["64k", 65536],
	["exact-chunk", CHUNK_SIZE],
	["multi-chunk", CHUNK_SIZE + 7],
] as const) {
	const seed = `stolnk-vector-${label}`;
	const plaintext = await seededBytes(seed, size);
	const id = toBase64Url(crypto.getRandomValues(new Uint8Array(16)));
	const ciphertext = await encryptStream(contentKey, noncePrefix, id, plaintext);
	const inline = size <= 65536;
	vectors.push({
		label,
		file_id: id,
		size,
		...(inline ? { plaintext: toBase64Url(plaintext) } : { seed }),
		ciphertext: toBase64Url(ciphertext),
		plain_sha256: toHex(await crypto.subtle.digest("SHA-256", plaintext as BufferSource)),
		chunk_count: chunkCountFor(size),
	});
}

// A ciphertext with one flipped bit inside the first chunk's body. Decryption
// must reject it outright rather than yield 1023 correct bytes (PRD 9.3).
const tampered = fromBase64Url(vectors[2].ciphertext);
tampered[10] ^= 0x01;

const out = {
	note: "Generated by scripts/gen-vectors.ts. See docs/wire-format.md.",
	kek_info: "stolnk/v1/kek",
	chunk_size: CHUNK_SIZE,
	recipient: {
		// 32-byte scalar, the form CryptoKit's `rawRepresentation` initialiser wants.
		private_raw: recipientJwk.d,
		public_raw: recipientPubRaw,
	},
	envelope: {
		wrapped_key: envelope.wrapped_key,
		key_iv: envelope.key_iv,
		eph_pub: envelope.eph_pub,
		nonce_prefix: envelope.nonce_prefix,
		expected_content_key: toBase64Url(contentKeyRaw),
	},
	filename: {
		plaintext: filename,
		enc_name: name.enc_name,
		name_iv: name.name_iv,
	},
	file_id_sample: fileId,
	vectors,
	tampered: {
		from: vectors[2].label,
		file_id: vectors[2].file_id,
		size: vectors[2].size,
		ciphertext: toBase64Url(tampered),
	},
};

writeFileSync(
	new URL("../../testdata/vectors.json", import.meta.url),
	`${JSON.stringify(out, null, "\t")}\n`,
);

// Self-check: the generator must be able to read back what it just produced.
const reimported = await importContentKey(contentKeyRaw);
if (!reimported) throw new Error("content key did not re-import");
console.log(`wrote ${vectors.length} vectors, largest ${vectors.at(-1)!.size} bytes`);
