#!/bin/bash
#
# The Worker's secrets, in both places they live.
#
#   ./scripts/secrets.sh init    write a fresh .dev.vars for local development
#   ./scripts/secrets.sh check   report which secrets production is missing
#   ./scripts/secrets.sh push    set the missing ones on production
#   ./scripts/secrets.sh push --rotate
#                                replace them even if already set
#
# Secrets are generated here and piped straight into wrangler: the value is
# never printed, never written to a file for production, and never pasted by
# hand. SESSION_SECRET only signs session tokens, so nothing needs a copy of it
# — rotating just makes every device re-authenticate, which the Mac app does
# silently against its Secure Enclave key.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Every secret the Worker reads from its environment. Anything that is the same
# for every deploy and is not sensitive belongs in src/shared/site-origin.ts or
# wrangler.json instead, not here.
SECRETS=(SESSION_SECRET)

generate() { openssl rand -base64 32; }

# `wrangler secret list` prints a JSON array of {name, type}.
remote_names() {
	npx wrangler secret list 2>/dev/null |
		python3 -c 'import json,sys
raw = sys.stdin.read()
start = raw.find("[")
print("\n".join(e["name"] for e in json.loads(raw[start:] if start >= 0 else "[]")))' 2>/dev/null || true
}

cmd_init() {
	if [ -f .dev.vars ]; then
		echo ".dev.vars already exists — delete it first to regenerate" >&2
		exit 1
	fi
	{
		echo "# Generated by scripts/secrets.sh. Local development only."
		for name in "${SECRETS[@]}"; do echo "$name=\"$(generate)\""; done
	} > .dev.vars
	echo "wrote .dev.vars with ${#SECRETS[@]} generated secret(s)"
}

cmd_check() {
	local present
	present="$(remote_names)"
	local missing=0
	for name in "${SECRETS[@]}"; do
		if grep -qx "$name" <<<"$present"; then
			echo "  set      $name"
		else
			echo "  MISSING  $name"
			missing=$((missing + 1))
		fi
	done
	[ "$missing" -eq 0 ] || echo "$missing secret(s) missing — run: npm run secrets:push"
	return 0
}

cmd_push() {
	local rotate="${1:-}"
	local present
	present="$(remote_names)"
	for name in "${SECRETS[@]}"; do
		if grep -qx "$name" <<<"$present" && [ "$rotate" != "--rotate" ]; then
			echo "  skip     $name (already set; pass --rotate to replace)"
			continue
		fi
		# The value goes down the pipe and is never echoed.
		generate | npx wrangler secret put "$name" >/dev/null
		echo "  pushed   $name"
	done
	echo
	echo "Secrets take effect immediately — no redeploy needed."
}

case "${1:-}" in
	init) cmd_init ;;
	check) cmd_check ;;
	push) cmd_push "${2:-}" ;;
	*)
		echo "usage: $0 {init|check|push [--rotate]}" >&2
		exit 2
		;;
esac
