#!/bin/bash
#
# The Worker's secrets, in both places they live.
#
#   ./scripts/secrets.sh init    write a fresh .dev.vars for local development
#   ./scripts/secrets.sh check   report which secrets production is missing
#   ./scripts/secrets.sh push    set the missing ones on production
#   ./scripts/secrets.sh push --rotate
#                                replace them even if already set
#
# There are two kinds. Generated secrets are made here and piped straight into
# wrangler: the value is never printed, never written to a file for production,
# and never pasted by hand. SESSION_SECRET is the only one — it signs session
# tokens, so nothing needs a copy, and rotating it just makes every device
# re-authenticate, which the Mac app does silently against its Secure Enclave
# key.
#
# Supplied secrets come from somewhere else and cannot be invented: the Creem
# pair is issued by Creem (PRD 16.5). `push` hands those to wrangler's own
# prompt, so they are typed into wrangler and not into this script, a shell
# history, or a file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Every secret the Worker reads from its environment. Anything that is the same
# for every deploy and is not sensitive belongs in src/shared/site-origin.ts or
# wrangler.json instead, not here.
GENERATED=(SESSION_SECRET)

# Read from Creem's dashboard (PRD 16.5). The API key authenticates us to Creem;
# the webhook secret is the only thing standing between the refund endpoint and
# anyone who can POST to it.
#
# The product id and discount code are not sensitive — the buyer reads both off
# the checkout URL — and by the comment above they would belong in wrangler.json.
# They are here anyway, because `wrangler types` gives a var the literal type of
# its value, so an unset one types as `""` and every `if (!env.X)` guard in the
# code becomes statically dead. One mechanism for all four is worth more than
# the distinction.
#
# CREEM_DISCOUNT_CODE is optional: unset simply means the early-bird run
# (PRD 16.1) is over and checkout goes to the full price.
SUPPLIED=(CREEM_API_KEY CREEM_WEBHOOK_SECRET CREEM_PRODUCT_ID CREEM_DISCOUNT_CODE)

# Absent is a valid state for these, so `check` reports them without counting
# them as missing.
OPTIONAL=(CREEM_DISCOUNT_CODE)

SECRETS=("${GENERATED[@]}" "${SUPPLIED[@]}")

generate() { openssl rand -base64 32; }

# `wrangler secret list` prints a JSON array of {name, type}.
remote_names() {
	npx wrangler secret list 2>/dev/null |
		python3 -c 'import json,sys
raw = sys.stdin.read()
start = raw.find("[")
print("\n".join(e["name"] for e in json.loads(raw[start:] if start >= 0 else "[]")))' 2>/dev/null || true
}

cmd_init() {
	if [ -f .dev.vars ]; then
		echo ".dev.vars already exists — delete it first to regenerate" >&2
		exit 1
	fi
	{
		echo "# Generated by scripts/secrets.sh. Local development only."
		for name in "${GENERATED[@]}"; do echo "$name=\"$(generate)\""; done
		echo
		echo "# Local development points at the stub Creem that scripts/e2e.ts"
		echo "# starts, so the purchase path can be exercised without an account and"
		echo "# without charging anything. With the stub not running, activation"
		echo "# fails with 503 and every device behaves as Free — which is also a"
		echo "# realistic thing to develop against."
		echo "CREEM_API_KEY=\"dev\""
		echo "CREEM_API_BASE=\"http://127.0.0.1:5199\""
		echo "CREEM_PRODUCT_ID=\"dev-product\""
		echo "CREEM_WEBHOOK_SECRET=\"$(generate)\""
	} > .dev.vars
	echo "wrote .dev.vars — ${#GENERATED[@]} generated, ${#SUPPLIED[@]} to fill in by hand"
}

cmd_check() {
	local present
	present="$(remote_names)"
	local missing=0
	for name in "${SECRETS[@]}"; do
		if grep -qx "$name" <<<"$present"; then
			echo "  set      $name"
		elif [[ " ${OPTIONAL[*]} " == *" $name "* ]]; then
			echo "  unset    $name (optional)"
		else
			echo "  MISSING  $name"
			missing=$((missing + 1))
		fi
	done
	[ "$missing" -eq 0 ] || echo "$missing secret(s) missing — run: npm run secrets:push"
	return 0
}

cmd_push() {
	local rotate="${1:-}"
	local present
	present="$(remote_names)"
	for name in "${SECRETS[@]}"; do
		if grep -qx "$name" <<<"$present" && [ "$rotate" != "--rotate" ]; then
			echo "  skip     $name (already set; pass --rotate to replace)"
			continue
		fi
		if [[ " ${SUPPLIED[*]} " == *" $name "* ]]; then
			local hint="from the Creem dashboard"
			[[ " ${OPTIONAL[*]} " == *" $name "* ]] && hint="$hint; optional — Ctrl-C to skip"
			# No pipe: wrangler prompts, so the value is never an argument to this
			# script and never lands in shell history.
			echo "  enter    $name ($hint)"
			npx wrangler secret put "$name" >/dev/null || {
				echo "  skipped  $name"
				continue
			}
		else
			# The value goes down the pipe and is never echoed.
			generate | npx wrangler secret put "$name" >/dev/null
		fi
		echo "  pushed   $name"
	done
	echo
	echo "Secrets take effect immediately — no redeploy needed."
}

case "${1:-}" in
	init) cmd_init ;;
	check) cmd_check ;;
	push) cmd_push "${2:-}" ;;
	*)
		echo "usage: $0 {init|check|push [--rotate]}" >&2
		exit 2
		;;
esac
