#!/bin/bash
#
# The Worker's secrets, in both places they live.
#
#   ./scripts/secrets.sh init    write a fresh .dev.vars for local development
#   ./scripts/secrets.sh check   report which secrets production is missing
#   ./scripts/secrets.sh push    overwrite production values from .dev.vars
#
# There are two kinds. Generated secrets are created by `init` and stored only
# in the git-ignored .dev.vars file. SESSION_SECRET is the only one — it signs
# session tokens, and replacing it makes every device re-authenticate, which
# the Mac app does silently against its Secure Enclave key.
#
# Supplied secrets come from somewhere else and cannot be invented: the Creem
# pair is issued by Creem (PRD 16.5). Local development keeps all Worker
# configuration in the git-ignored .dev.vars file. `push` sends that file to
# Wrangler's bulk secret endpoint so values never appear in command arguments
# or this script's output.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Every secret the Worker reads from its environment. Anything that is the same
# for every deploy and is not sensitive belongs in src/shared/site-origin.ts or
# wrangler.json instead, not here.
GENERATED=(SESSION_SECRET)

# Read from Creem's dashboard (PRD 16.5). The API key authenticates us to Creem;
# the webhook secret is the only thing standing between the refund endpoint and
# anyone who can POST to it.
#
# The product id and discount code are not sensitive — the buyer reads both off
# the checkout URL — and by the comment above they would belong in wrangler.json.
# They are here anyway, because `wrangler types` gives a var the literal type of
# its value, so an unset one types as `""` and every `if (!env.X)` guard in the
# code becomes statically dead. One mechanism for all four is worth more than
# the distinction.
#
# CREEM_DISCOUNT_CODE is optional: unset simply means the early-bird run
# (PRD 16.1) is over and checkout goes to the full price.
SUPPLIED=(CREEM_API_KEY CREEM_WEBHOOK_SECRET CREEM_PRODUCT_ID CREEM_DISCOUNT_CODE)

# Absent is a valid state for these, so `check` reports them without counting
# them as missing.
OPTIONAL=(CREEM_DISCOUNT_CODE)

SECRETS=("${GENERATED[@]}" "${SUPPLIED[@]}")

generate() { openssl rand -base64 32; }

# `wrangler secret list` prints a JSON array of {name, type}.
remote_names() {
	npx wrangler secret list 2>/dev/null |
		python3 -c 'import json,sys
raw = sys.stdin.read()
start = raw.find("[")
print("\n".join(e["name"] for e in json.loads(raw[start:] if start >= 0 else "[]")))' 2>/dev/null || true
}

cmd_init() {
	if [ -f .dev.vars ]; then
		echo ".dev.vars already exists — delete it first to regenerate" >&2
		exit 1
	fi
	{
		echo "# Generated by scripts/secrets.sh. Local development only."
		for name in "${GENERATED[@]}"; do echo "$name=\"$(generate)\""; done
		echo
		echo "# Local development points at the stub Creem that scripts/e2e.ts"
		echo "# starts, so the purchase path can be exercised without an account and"
		echo "# without charging anything. With the stub not running, activation"
		echo "# fails with 503 and every device behaves as Free — which is also a"
		echo "# realistic thing to develop against."
		echo "CREEM_API_KEY=\"dev\""
		echo "CREEM_API_BASE=\"http://127.0.0.1:5199\""
		echo "CREEM_CHECKOUT_BASE=\"https://www.creem.io/test/payment\""
		echo "CREEM_PRODUCT_ID=\"dev-product\""
		echo "CREEM_DISCOUNT_CODE=\"\""
		echo "CREEM_WEBHOOK_SECRET=\"$(generate)\""
	} > .dev.vars
	echo "wrote .dev.vars — ${#GENERATED[@]} generated, ${#SUPPLIED[@]} to fill in by hand"
}

cmd_check() {
	local present
	present="$(remote_names)"
	local missing=0
	for name in "${SECRETS[@]}"; do
		if grep -qx "$name" <<<"$present"; then
			echo "  set      $name"
		elif [[ " ${OPTIONAL[*]} " == *" $name "* ]]; then
			echo "  unset    $name (optional)"
		else
			echo "  MISSING  $name"
			missing=$((missing + 1))
		fi
	done
	[ "$missing" -eq 0 ] || echo "$missing secret(s) missing — run: npm run secrets:push"
	return 0
}

cmd_push() {
	if [ ! -f .dev.vars ]; then
		echo ".dev.vars not found — create it before pushing secrets" >&2
		exit 1
	fi

	# Wrangler accepts dotenv files directly. Every key in .dev.vars is created
	# or overwritten in one request; remote keys absent from the file are kept.
	npx wrangler secret bulk .dev.vars >/dev/null
	echo "pushed all values from .dev.vars"
	echo
	echo "Secrets take effect immediately — no redeploy needed."
}

case "${1:-}" in
	init) cmd_init ;;
	check) cmd_check ;;
	push) cmd_push ;;
	*)
		echo "usage: $0 {init|check|push}" >&2
		exit 2
		;;
esac
